name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run checks
      run: make check

    - name: Run distribution checks
      run: make distcheck

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          **/node_modules
          **/dist
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
